### ISSUE TITLE
use scattered writev/readv as primitive

### ISSUE THREAD

**Issue by MartinNowak** [jasonwhite/io#1]
Several unix platforms support scattered reads and writes through `writev` and `readv`.
I think choosing these as basic I/O primitives would be an excellent match for D's typesafe variadic functions and provide a good advantage for some operations.
For example writing a complete ring buffer would be possible w/ a single syscall.

``` d
writev(buf[rpos .. $], buf[0 .. wpos]);
```

The overhead of converting the slices to iovecs (using a fixed stack buffer) is neglectable compared to the cost of a syscall. So I'd suggest the following function signatures as IO primitives.

``` d
size_t writev(in ubyte[][] bufs...);
size_t readv(scope ubyte[][] bufs...);
```

Also IO should use `ubyte[]` instead of `void[]` arrays b/c the latter is scanned for pointers by the GC, but IO only deals w/ serialized data.

**Comment by jasonwhite** [comment]
How's this for writev? 6cfb0af8bea82503fe81646e47f61bc74aef5c1d Unfortunately, to avoid heap allocations, it can potentially take multiple `writev` passes to write everything. This negates some of the atomic guarantees that `writev` has. It might be better to use the stack-allocated `iov` and fallback to a heap allocated version if there are too many vector elements.

I didn't know that about `void[]` getting scanned by the GC. I did it that way so regular strings could also get conveniently passed to `write()`. I'll look into changing that.

**Comment by MartinNowak** [comment]
> It might be better to use the stack-allocated iov and fallback to a heap allocated version if there are too many vector elements.

Right, malloc is cheap enough when you have many buffers.
Unfortunately length and ptr of iovec is just the opposite of D's arrays, otherwise one could've reinterpreted the argument ;).

> I did it that way so regular strings could also get conveniently passed to write().

Maybe leave that to the buffering layer or add a module level UFCS function for that.

``` d
void write(IO)(ref IO io, in char[] s)
{
    io.writev(cast(const(ubyte)[])s);
}

unittest
{
    File file;
    file.write("It works");
}
```

**Comment by jasonwhite** [comment]
> Right, malloc is cheap enough when you have many buffers.

Done: 303268b61a9c42d72e6c27b43dab831e7deb1eb3 :) I'm not quite sure what an optimal default should be for the stack size. 32 should be plenty big for most use cases.

> Maybe leave that to the buffering layer or add a module level UFCS function for that.

I agree. I'll see about implementing that later when I have time.

Thanks for the feedback!

**Comment by MartinNowak** [comment]
I missed sth., the arguments should be `scope` so it's clear that escaping the array isn't allowed.
See [Issue 5212 – no escape analysis for typesafe variadic function arguments](https://issues.dlang.org/show_bug.cgi?id=5212#c15)

**Comment by jasonwhite** [comment]
I thought `in` was equivalent to `const scope`, so it shouldn't be necessary? See https://dlang.org/spec/function.html#parameters (assuming that documentation is correct).

**Comment by jasonwhite** [comment]
`read()`/`write()` now take `ubyte[]` instead of `void[]`. Also added `scope` to `read()` and `readv()`.
