### ISSUE TITLE
can I replace your io package on code.dlang.org?

### ISSUE THREAD

**Issue by MartinNowak** [jasonwhite/io#10]
FWIW this package is now unmaintained and seems unused.
https://code.dlang.org/packages/io
Based on your initial ideas and some discussion, I've written http://github.com/MartinNowak/io for which I hope it will become std.io in the long-term.

You should be able to unregister your package under https://code.dlang.org/my_packages/io after logging in.

**Comment by jasonwhite** [comment]
Absolutely! I deleted my `io` package. Good luck with your library!

I have since jumped ship to Rust, but it'd be great for D to finally have a decent IO story.

**Comment by jasonwhite** [comment]
I also added a note to the README directing people to your library.
