### ISSUE TITLE
stdout threadsafe?

### ISSUE THREAD

**Issue by rjmcguire** [jasonwhite/io#8]
Are io streams threadsafe on Linux? I'm getting a weird issue with println if I use it in two threads, swapping between one and then the other in a asynchronous app.

I'm wondering if I need to make sure all output goes through the same thread.
Not asking you to make the library thread-safe, just checking if it is.

Thanks!

**Comment by jasonwhite** [comment]
No, streams are not thread-safe. You'll have to use `synchronized` statements (or some other mechanism) to avoid interleaving output. It'll also probably crash if the stream is buffered.

I think it's bad practice to write output on multiple threads, but I understand that it is sometimes unavoidable. It's kind of like updating a GUI from multiple threads. Usually there is one thread dedicated to displaying the GUI and all other threads are just worker threads.

I've pondered adding a locking mechanism to streams, but haven't come up with a pleasant way of doing it yet. Any suggestions would be appreciated!

**Comment by MartinNowak** [comment]
Isn't that usually done by locking the file descriptor?

**Comment by jasonwhite** [comment]
@MartinNowak I'm not sure what the common practice is. File descriptor locking has some quirks, so I expect that it isn't normally used to order reads/writes within a single process.

FYI, I've since abandoned D for Rust, so this project isn't maintained anymore.
